name: CI

on:
  push:
    branches: "*"
  pull_request:
    branches: master

jobs:
  test:
    name: ${{ matrix.python-version }}-build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]
    steps:
      - uses: actions/checkout@v4.1.4
      - name: Setup Python
        uses: actions/setup-python@v2.3.1
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - uses: actions/cache@v2.1.7
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/dev-requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - run: |
          python -m pip install -r dev-requirements.txt
          python -m pip install --no-deps -e .
          python -m pip list
      - name: Running Tests
        run: |
          python -m pytest --mypy --flake8 --junitxml=test-reports/junit.xml --cov=./ --verbose dac_costing
    #   - name: Upload coverage to Codecov
    #     uses: codecov/codecov-action@v1
    #     with:
    #       file: test-reports/junit.xml
